name: smartagri
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/
    - asset/fonts/
    - asset/image/

  fonts:
    - family: dancing script
      fonts:
        - asset: asset/fonts/DancingScript-Regular.ttf
        - asset: asset/fonts/DancingScript-Medium.ttf
          weight: 500
        - asset: asset/fonts/DancingScript-Bold.ttf
          weight: 700