name: smartagri
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  image_picker: ^1.1.2
  phone_form_field: ^9.2.7
  provider: ^6.1.2
  razorpay_flutter: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/
    - asset/fonts/
    - asset/image/

  fonts:
    - family: dancing script
      fonts:
        - asset: asset/fonts/DancingScript-Regular.ttf
        - asset: asset/fonts/DancingScript-Medium.ttf
          weight: 500
        - asset: asset/fonts/DancingScript-Bold.ttf
          weight: 700